# i love experimenting with github actions
name: Build CDI (KallistiOS)
on:
  push:
    branches: [ dreamcast ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nold360/kallistios-sdk:latest
    steps:
      - name: Source KOS env
        run: . /opt/toolchains/dc/kos/environ.sh
      - name: Compile & mkdcdisc (CDI)
        run: cd ${{ github.workspace }} && make -j$(nproc)
      - name: Upload CDI
        uses: actions/upload-artifact@v7.0.1
        with:
          name: CDI Image (for burning or emulation)
          path: ${{ github.workspace }}/build/fnf.cdi
