# i love experimenting with github actions
name: Build CDI (KallistiOS)
on:
  push:
    branches: [ dreamcast ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: nold360/kallistios-sdk:latest
    steps:
      - name: Source KOS env
        run: source /opt/toolchains/dc/kos/environ.sh
      - name: Compile & mkdcdisc (CDI)
        run: make -j$(nproc)
      - name: Upload CDI
        uses: actions/upload-artifact@v7.0.1
        with:
          name: CDI Image (for burning or emulation)
          path: ${{ github.workspace }}/build/fnf.cdi
